### ISSUE TITLE
Accessories show "No Response" - until you tap on them

### ISSUE THREAD

**Issue by bdruth** [nfarina/homebridge#1366]
I've seen many folks having an issue where accessories appear to stop working. I've also seen that nuke & paving seems to get things working again. What I haven't seen is any mention of what I recently noticed ... if I tap the accessory (in my case, a smart plug) - after either 1 or 2 taps (seems random) - the accessory returns to being responsive in Home (from my iPhone).

In my particular case, accessories will return to "No Response" after a fairly short time - not days or weeks - more like minutes.

Has anyone else that's seeing these "No Response" issues also seeing this?

**Comment by bdruth** [comment]
I just checked w/ Siri and the same holds true.
> Siri, is the ``<<accessory name>>`` on?

Siri says it can't communicate with it
> Siri, is the ``<<accessor name>>`` on?

Siri correctly returns the status.

**Comment by sendorm** [comment]
After giving a fixed ip address to the rm pro hub from the router, this problem is fixed in my setup. The hub was using the same ip anyway, nevertheless setting a fix ip smoothed the experience.

**Comment by mynameisdaniel32** [comment]
I've also been experiencing this issue as bdruth has described it for the last few weeks. I thought it was an iOS11 beta bug but it's still occurring on the iOS beta 3 which is fairly stable.

**Comment by DiMarcello77** [comment]
Hello All, I had this same issue and I solved it today. homebridge was found but all accesoires where 'Not Responding' 

I thought it was because of an IOS 11 update first but after completely removing / reinstalling my PI3 with homebridge the issue was still there. I googled a lot and in my case my router (Netgear Orbi) had this multicast feature set to **disabled**: 

_Disable IGMP Proxying. IGMP proxying allows a computer on the local area network (LAN) to receive the multicast traffic it is interested in from the Internet._

After enabling this multicast feature and rebooting the router it was completely running fine again!

It's unknown to me why this setting was disabled but now it is working like a charm again :-) 

Keep up the good work nfarina! I love homebridge!

**Comment by wapster182** [comment]
> I thought it was because of an IOS 11 update first but after completely removing / reinstalling my PI3 with homebridge the issue was still there. I googled a lot and in my case my router (Netgear Orbi) had this multicast feature set to **disabled**:
> 
> _Disable IGMP Proxying. IGMP proxying allows a computer on the local area network (LAN) to receive the multicast traffic it is interested in from the Internet._
> 
> After enabling this multicast feature and rebooting the router it was completely running fine again!
> 
> It's unknown to me why this setting was disabled but now it is working like a charm again :-)


This helped me a lot! I had the same issue, my sd card died and after restoring a backup to a new card all devices where not responding. The real issue was a Netgear Orbi Update that disabled the IGMP Proxy setting. After enabling, everything is fine now. I am so thankful for your post, this was bugging me for weeks!
