### ISSUE TITLE
Suddenly "No Response" from devices after running well for a few minutes

### ISSUE THREAD

**Issue by RealDeemer** [nfarina/homebridge#1390]
I expedience a strange behavior after running the home bridge for about 1 year without issues.

All my devices (including the bridge) show up disabled in the Home App. They are labeled with "**No Response**".

The strange thing is that this worked until last week. Other findings:
- The Homebridge seems to run fine. It does not show any issues or errors (nothing in the error log, nothing in the log)
- Rebooting iOS devices and the Bridge does not bring the devices back, still "No Response"
- Disabling plugins does not change anything
- Deleting the persistent folder and the accessories folder and restarting home bridge does not change anything
- Reverting a backup does not change anything
- Reinstalling the homebridge and the plugins does not change anything
- Deleting the home and and creating a new home does not change anything

However, there is one combination that brings back the devices for a couple of minutes:
- Stopping the homebridge
- Removing the bridge from HomeKit
- Deleting persistence and accessories 
- Starting the homebridge
- Adding the bridge to HomeKit

This brings back all devices and accessories for a couple of minutes. After then they go grey again with the obvious "**No Response**".

And just to avoid confusion, a ps showed the homebridge running, while the devices do not respond. 

Is there a way how I can troubleshoot this. Is there a verbose log that I could enable?

I keeping that system for the next couple of days to perform troubleshoot tasks. After then I am removing the system and set up a new homebridge.

**Comment by RealDeemer** [comment]
All,

I was able to identify the homematic plugin as a source for the issue. This plugin causes devices from other plug-ins to appear in the described state. I assume this can be closed here.

**Comment by timokli** [comment]
Which plugin was the cause?

**Comment by RealDeemer** [comment]
Hi,

it seems that **homebridge-homematic** caused the issue. The Homematic plugin added 69 devices to my home and it seems that some of the devices have not been responsive which somehow had impact to all devices in all plugins.

I did now clear up my device list in Homematic and add new devices subsequently, so far the whole installation works fine.

**Comment by NebzHB** [comment]
I had the same problem with my plugin... it seems i was sometimes sending invalid data to homebridge, i've fix that with sanitizing all data i send to homebridge #1367

**Comment by timokli** [comment]
@RealDeemer That is very interesting, because I have the same problem with my homebridge installation and so far I didnt know where the reason for unresponsive devices was coming from. I am using homebrige-homematic, too. In my case with round about 50 devices.

I would suggest to share your informations and logs regarding this directly to the plugin developer https://github.com/thkl/homebridge-homematic

I will do it, too :)

**Comment by nicoh88** [comment]
@timokli @NebzHB @RealDeemer  

**A few questions about the cause of the "no response" problem:**
1. Which plugins are configured in your config.json (`npm -g list | grep -i homebridge`)?
2. Do you have an original [Philips Hue Bridge](https://www.howtogeek.com/wp-content/uploads/2015/10/ximg_561e966beee38.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.O2B_X_9wwF.png) on HomeKit in use?
3. Do you have an [HA-Bridge](https://github.com/bwssytems/ha-bridge) in use?
4. Do you have a [Devolo HomeControl](http://www.devolo.de/home-control/)?
5. Do you have an AppleTV or iPad as a HomeKit Home Hub in use? If so, which device and which iOS version?

**My answer:** 
1. homebridge-cmdswitch2, homebridge-devolo, homebridge-fritz, homebridge-harmonyhub, homebridge-homematic, homebridge-neato, homebridge-netatmo, homebridge-samsungtv-control, homebridge-sonos, homebridge-sonybraviatv, homebridge-vorwerk
2. Yes, v2.
3. [Yes, for my logitech harmony hub](https://www.loggn.de/logitech-harmony-companion-haussteuerungstasten-fremd-belegen-ha-bridge/).
4. Yes.
5. Yes. 
5.1. Home Hub: iPad mini 3 with iOS 10.3.3.
5.2. Client Devices: iPhone 7 with iOS 11b5 and iPad Air 2 with iOS 11b5.

**Comment by RealDeemer** [comment]
Sorry for the late answer, I have been traveling a lot during the last week. See my answer below:

**Which plugins are configured in your config.json (npm -g list | grep -i homebridge)?**

`
pi@homebridgepi:~ $ npm -g list | grep -i homebridge
├─┬ homebridge@0.4.22
├─┬ homebridge-camera-ffmpeg@0.1.0
├─┬ homebridge-custom-http@0.1.7
├─┬ homebridge-doorbird@0.0.3
├─┬ homebridge-harmonyhub@0.2.0
├─┬ homebridge-homematic@0.0.76
├─┬ homebridge-sonos@0.2.2
`
However, I did a lot of testing. Even while all these modules have been installed, I did my testing with a home bridge/config.json that just contained the configuration for the homebridge-homematic. I really guess that homematic causes that issue more or less.

Keep in mind, the issue reappears, when I add more than 50 devices to my homebridge-homematic. I currently do not have added the sensors (humidity, movement, temperature) to my homebridge configuration. I did not see the issue again with that limited configuration.

Als strange, when I am set up the homematic Bridget to my home bridge the HomeKit assistant asks me to configure each device (i.e. assign it to a room) after adding that significant number of devices the assistant goes crazy. It first represents me items that I had configured a minute ago. Then, a bit later, it doesn't allow me to assign the devices to rooms anymore. It simply reverts to default once I have chosen the room from the room selector dialog. 

When I den cancel the assistant all devices, even the ones that are not connected over the bridge.

**Do you have an original Philips Hue Bridge on HomeKit in use?**

No.

**Do you have an HA-Bridge in use?**

Well, homebridge-homematic is essentially a HA-Bridge.

Once I get the "No Response" issue I have to remove that HA-Bridge from my home to get it running again.

**Do you have a Devolo HomeControl?**

No.

**Do you have an AppleTV or iPad as a HomeKit Home Hub in use? If so, which device and which iOS version?**

Yes. I have a ATV4 with latest tvOS10 running. I plugged that off during my testing. I am getting the No Response issue even then there is no ATV4 available.

**Comment by nicoh88** [comment]
@timokli @NebzHB @RealDeemer
Problem was solved by @pdlove - [here](https://github.com/nfarina/homebridge/issues/1418#issuecomment-322669553).

**Update homebridge**
`npm -g update homebridge`

**Comment by RealDeemer** [comment]
I would not consider this as resolved. I've added some sensors a few days ago which gives me now a total of 67 devices. Finally the no response issue is back:

`
pi@homebridgepi:~ $ homebridge 
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[9/3/2017, 5:10:11 PM] Loaded plugin: homebridge-camera-ffmpeg
[9/3/2017, 5:10:11 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[9/3/2017, 5:10:11 PM] ---
[9/3/2017, 5:10:12 PM] Loaded plugin: homebridge-custom-http
[9/3/2017, 5:10:12 PM] Registering accessory 'homebridge-custom-http.Custom-Http'
[9/3/2017, 5:10:12 PM] ---
[9/3/2017, 5:10:13 PM] Loaded plugin: homebridge-doorbird
[9/3/2017, 5:10:13 PM] Registering platform 'homebridge-doorbird.DoorBird'
[9/3/2017, 5:10:13 PM] ---
[9/3/2017, 5:10:13 PM] Loaded plugin: homebridge-harmonyhub
[9/3/2017, 5:10:14 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[9/3/2017, 5:10:14 PM] ---
[9/3/2017, 5:10:15 PM] Loaded plugin: homebridge-homematic
[9/3/2017, 5:10:15 PM] Registering platform 'homebridge-homematic.HomeMatic'
[9/3/2017, 5:10:15 PM] ---
[9/3/2017, 5:10:15 PM] Loaded plugin: homebridge-sonos
[9/3/2017, 5:10:15 PM] Registering accessory 'homebridge-sonos.Sonos'
[9/3/2017, 5:10:15 PM] ---
[9/3/2017, 5:10:15 PM] Loaded config.json with 1 accessories and 2 platforms.
[9/3/2017, 5:10:15 PM] ---
[9/3/2017, 5:10:15 PM] Loading 2 platforms...
[9/3/2017, 5:10:15 PM] [HomeMatic CCU] Initializing HomeMatic platform...
[9/3/2017, 5:10:15 PM] [HomeMatic CCU] Homematic Plugin Version 0.0.76
[9/3/2017, 5:10:15 PM] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[9/3/2017, 5:10:15 PM] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[9/3/2017, 5:10:15 PM] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[9/3/2017, 5:10:15 PM] [HomeMatic CCU] will connect to your ccu at 192.168.24.9
[9/3/2017, 5:10:16 PM] [HomeMatic CCU] using binrpc for communication with BidCos-RF
[9/3/2017, 5:10:16 PM] [HomeMatic CCU] init RPC for BidCos-RF.
[9/3/2017, 5:10:16 PM] [HomeMatic CCU] Fetching Homematic devices...
[9/3/2017, 5:10:16 PM] Initializing DoorBird platform...
[9/3/2017, 5:10:16 PM] Starting discovery...
[9/3/2017, 5:10:16 PM] Starting a homebridge-doorbird device with name 'DoorBird'...
[9/3/2017, 5:10:16 PM] HTTP Server started on port 8080
[9/3/2017, 5:10:16 PM] Initializing platform accessory 'DoorBird'...
[9/3/2017, 5:10:16 PM] Loading 1 accessories...
[9/3/2017, 5:10:16 PM] [Radio] Initializing Sonos accessory...
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-harmonyhub.HarmonyHub
[9/3/2017, 5:10:16 PM] [homebridge-harmonyhub.HarmonyHub] Ignoring Harmony Platform setup because it is not configured
[9/3/2017, 5:10:16 PM] [HomeMatic CCU] RPC server for interface BidCos-RF. is listening on port 9090.
[9/3/2017, 5:10:16 PM] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[9/3/2017, 5:10:16 PM] [HomeMatic CCU] if PONG is PONG CCU is alive
[9/3/2017, 5:10:16 PM] [Radio] Found a playable coordinator device at 192.168.24.31 in zone 'Küche' for accessory 'Radio' in accessory room 'Küche'
[9/3/2017, 5:10:25 PM] [HomeMatic CCU] Fetch Response
[9/3/2017, 5:10:25 PM] [HomeMatic CCU] Program 61 Gute Nacht, Lichter Aus added as SWITCH cause of IOS 10
[9/3/2017, 5:10:25 PM] [HomeMatic CCU] Initializing platform accessory ...
...
(Removed a bunch of accessories)
...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 013-81-072 │     
    └────────────┘     
                       
[9/3/2017, 5:10:25 PM] [HomeMatic CCU] Number of mapped devices : 68
[9/3/2017, 5:10:25 PM] Homebridge is running on port 51826.
[9/3/2017, 5:10:25 PM] [HomeMatic CCU] NPM 0.0.76 vs Local 0.0.76
[9/3/2017, 5:10:25 PM] [HomeMatic CCU] will cache ccu response ...
`

![fullsizerender](https://user-images.githubusercontent.com/23310670/30004289-cface4f8-90cc-11e7-8052-a91026467e81.png)

**Comment by Buadhai** [comment]
Same issue here. The only plugin I'm using is Http. [https://www.npmjs.com/package/homebridge-http](url)

Installed it yesterday. Worked fine until we went to bed. Now, "No Response" from both the bridge and the single accessory I've installed.

Here's the config file:

```
{
    "bridge": {
        "name": "Koratbridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "Homebridge config file",

    "accessories": [
        {
            "accessory": "Http",
			"name": "Water Pump",
			"switchHandling": "realtime",
			"http_method": "GET",
			"on_url":      "http://192.168.0.55/cgi-bin/relaynew.cgi?on",
			"off_url":     "http://192.168.0.55/cgi-bin/relaynew.cgi?off",
			"status_url":  "http://192.168.0.55/cgi-bin/relaynew.cgi?state",
			"service": "Pump",
			"brightnessHandling": "no",
			"sendimmediately": "",
			"username" : "",
			"password" : ""
	  }
    ]
}

```

Here's a fragment of the log:

```
[2017-12-1 06:56:58] Loaded config.json with 1 accessories and 0 platforms.
[2017-12-1 06:56:58] ---
[2017-12-1 06:56:58] Loading 1 accessories...
[2017-12-1 06:56:58] [Water Pump] Initializing Http accessory...
[2017-12-1 06:57:09] Loaded plugin: homebridge-http
[2017-12-1 06:57:09] Registering accessory 'homebridge-http.Http'
[2017-12-1 06:57:09] ---
```

And here's the persistent entry in the error log:

```
TypeError: Cannot read property '0' of undefined
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:390:17)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:276:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
/usr/local/lib/node_modules/homebridge/lib/server.js:390
  if (!(services[0] instanceof Service)) {
                ^

```

The cgi URLs are working fine:

```
MrMuscle:.homebridge mnewman$ curl http://192.168.0.55/cgi-bin/relaynew.cgi?state
0
MrMuscle:.homebridge mnewman$ curl http://192.168.0.55/cgi-bin/relaynew.cgi?on
OK
MrMuscle:.homebridge mnewman$ curl http://192.168.0.55/cgi-bin/relaynew.cgi?state
1
MrMuscle:.homebridge mnewman$ curl http://192.168.0.55/cgi-bin/relaynew.cgi?off
OK
MrMuscle:.homebridge mnewman$ curl http://192.168.0.55/cgi-bin/relaynew.cgi?state
0
```

![2017-12-01 06 52 36](https://user-images.githubusercontent.com/34122609/33461496-4c7e022c-d665-11e7-9c49-e1e51fe36cdf.png)
