### ISSUE TITLE
Windows 10 install errors

### ISSUE THREAD

**Issue by NiackBuster** [nfarina/homebridge#690]
Hi guys, 
i have a clean install with Win10 by following the tutorial.
I well ran MSVS and i created a project and installed the C++...
My env variable seems to be good  as shown :
$ npm config get msvs_version
2015

but when i lanch npm install -g homebridge with git bash as admin) i get this (and same for npm install bignum) :

MINGW64 ~
$ npm install -g homebridge
C:\Users\thibaut\AppData\Roaming\npm\homebridge -> C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge

> bignum@0.12.5 install C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v47-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@5.0.0 (node-v47 ABI) (falling back to source compile with node-gyp)
G▒n▒ration des projets individuellement dans cette solution. Pour activer la g▒n▒ration en parall▒le, ajoutez le commutateur "/m".
  bignum.cc
  win_delay_load_hook.cc
..\bignum.cc(328): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(348): warning C4244: 'argument'▒: conversion de 'int64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(413): warning C4244: '='▒: conversion de 'double' en 'uint64_t', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(514): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(532): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(550): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(569): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(652): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(787): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
LINK : fatal error LNK1181: impossible d'ouvrir le fichier en entr▒e 'C:\OpenSSL-Win32\lib\libeay32.lib' [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\thibaut\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\thibaut\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "build" "--fallback-to-build" "--module=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node" "--module_name=bignum" "--module_path=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding"
gyp ERR! cwd C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\thibaut\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\thibaut\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding' (1)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\thibaut\npm-debug.log

[Uploading npm-debug.rar…]()

**Comment by PatcherMustermann** [comment]
Hello NiackBuster,
I think you should start again from the beginning. In addition, you must have the Windows-User administrator right and not "run as administrator". Read the instructions carefully!

Greeting
Patcher

**Comment by NiackBuster** [comment]
One question, i have the install of Windows 10 64bits
Should i follow the tutorial by installing all 32 bits versions of software
?

Le vendredi 1 juillet 2016, PatcherMustermann <notifications@github.com> a
écrit :

> Hello NiackBuster,
> I think you should start again from the beginning. In addition, you must
> have the Windows-User administrator right and not "run as administrator".
> Read the instructions carefully!
>
> Greeting
> Patcher
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nfarina/homebridge/issues/690#issuecomment-229879354>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APLDlDKJsgiD4Lg3wMSTwv-nr9KZydhPks5qRMVVgaJpZM4JCwyL>
> .
>


--

**Comment by PatcherMustermann** [comment]
Hello NiackBuster,
i have a Windows 7 64BIT and all Programs installed with 32BIT except Microsoft Visual Studio and Apple Bonjour. I have corrected my Howto ;)

Greeting
Patcher

**Comment by NiackBuster** [comment]
Hey ! Thanks for reply.

I Made a Clean install again with all the 32bits versions , i launched MsVs
to have the c++ tools and i still get an error with gyp... (Mostly the same
error as before)... My session is Administrator on the machine (only one
account)

I don't understand one thing about Python : "by user settings activate
path" what does IT mean ? I think i don't understand what to do

Do i have to specify : npm set --msvs version 2015 ?
Because If i do a "get version"in terminal there is no specified version.

Maby i Will Go on Ubuntu :-D or perhaps write a spécial tutorial for
Windows 10

Thanks for your support :)


Le vendredi 1 juillet 2016, PatcherMustermann <notifications@github.com> a
écrit :

> Hello NiackBuster,
> i have a Windows 7 64BIT and all Programs installed with 32BIT except
> Microsoft Visual Studio and Apple Bonjour. I have corrected my Howto ;)
>
> Greeting
> Patcher
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nfarina/homebridge/issues/690#issuecomment-230038455>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APLDlO61W5Fu66FqGARKa6fdVw2cDJQWks5qRXYCgaJpZM4JCwyL>
> .
>


--

**Comment by PatcherMustermann** [comment]
Hello NiackBuster,

> I don't understand one thing about Python : "by user settings activate path" what does IT mean ? I think i don't understand what to do

It must be set the system variable "path".

The following variables must be present:
...C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\nodejs\

Here is a link as you can see, the system variables:
[](http://www.computerhope.com/issues/ch000549.htm)


> Do i have to specify : npm set --msvs version 2015 ? Because If i do a "get version"in terminal there is no specified version.

I have nothing specified.

> Maby i Will Go on Ubuntu :-D or perhaps write a spécial tutorial for Windows 10

I have the "old" Homebridge run with Windows 10 64 BIT without problems.

Greeting
Patcher

**Comment by NiackBuster** [comment]
Yes I have TeamViewer, you would be ok to take the lead ?
I put all the variables for python but still :  

MINGW32 ~
$ npm install -g homebridge
C:\Users\thibaut\AppData\Roaming\npm\homebridge -> C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge

> bignum@0.12.5 install C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v47-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@5.0.0 (node-v47 ABI) (falling back to source compile with node-gyp)

C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding )  else (node  configure --fallback-to-build --module=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding )

C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding )  else (node  build --fallback-to-build --module=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding )
G▒n▒ration des projets individuellement dans cette solution. Pour activer la g▒n▒ration en parall▒le, ajoutez le commutateur "/m".
  bignum.cc
..\bignum.cc(328): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(348): warning C4244: 'argument'▒: conversion de 'int64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(413): warning C4244: '='▒: conversion de 'double' en 'uint64_t', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(514): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(532): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(550): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(569): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(652): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(787): warning C4244: 'argument'▒: conversion de 'uint64_t' en 'unsigned int', perte possible de donn▒es [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
  win_delay_load_hook.c
C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(31): error C2373: '__pfnDliNotifyHook2'▒: red▒finition▒; modificateurs de type diff▒rents [C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\build\bignum.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: voir la d▒claration de '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\thibaut\\AppData\\Roaming\\npm\\node_modules\\homebridge\\node_modules\\bignum\\binding\\bignum.node" "--module_name=bignum" "--module_path=C:\\Users\\thibaut\\AppData\\Roaming\\npm\\node_modules\\homebridge\\node_modules\\bignum\\binding"
gyp ERR! cwd C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\thibaut\\AppData\\Roaming\\npm\\node_modules\\homebridge\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\thibaut\AppData\Roaming\npm\node_modules\homebridge\node_modules\bignum\binding' (1)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\thibaut\npm-debug.log

**Comment by NiackBuster** [comment]
Patcher :-D ?

**Comment by PatcherMustermann** [comment]
@NiackBuster:
Sorry for my late reply. I was on a business trip abroad.
I have check my "bignum" version. I have 0.11.0 and you have 0.12.5. Maybe that is the problem?!

Greeting
Patcher

**Comment by gleep52** [comment]
This is all unfamiliar territory to me... I understand you have a different version, but that doesn't help me install it without instructions on how to bypass the error for the 12.5 version... :(  Can you help?

**Comment by roeshop** [comment]
I am a newbie with all of this and I'm trying to install -g homebridge.

I'm getting the exact some errors as indicated above is there a way to get around the bignum version??

**Comment by Bart274** [comment]
is this still not fixed? I want to use homebridge again, but I can't solve this issue :s

**Comment by jgrosstephanjr** [comment]
Any updates?

**Comment by alessiodionisi** [comment]
I solved the same problem on Linux by re-installing (and compiling) bignum.

```
cd ~/.nvm/versions/node/v6.5.0/lib/node_modules/homebridge
npm install bignum
```
